### ISSUE TITLE
Problem about input_azimuth_maps

### ISSUE THREAD

**Issue by NiPeiyuan** [PRIS-CV/NeRSP#5]
Hi~
Thanks for sharing the codes.

May I know how can I generate the input_azimuth_maps and normal_png for custom data of my own?

**Comment by Yu-fei-Han** [comment]
Due to inaccuracies in normals rendered by Mitsuba3, we have opted to use Blender for rendering, ensuring we maintain the same camera parameters. 

The `input_azimuth_maps` are calculated from `s1` and `s2` rendered using Mitsuba3. The specific equation used is:

` aop = 0.5 * arctan( s2 / s1 )`

For this calculation, you can simply use the mean values of `s1` and `s2` across their color channels, as we assume `aop` to be a scalar for each pixel.

**Comment by NiPeiyuan** [comment]
OK, Thank you for your quickly reply.
